base: configs/base.yaml

experiment_name: crnn_resnet_ctc

model:
  tps:
    enable: true
    num_fiducial: 20
    freeze_epochs: 10
  backbone:
    name: resnet34
    pretrained: true
    out_channels: 512
  sequence:
    hidden_size: 256
    num_layers: 2
    dropout: 0.1
  head:
    num_classes: 12
  label_smoothing: 0.1

train:
  data_dir: datav2/train
  label_file: datav2/train_labels.txt

eval:
  data_dir: datav2/val
  label_file: datav2/val_labels.txt

test:
  data_dir: datav2/test
  label_file: datav2/test_labels.txt
